Update patch set 3
Patch Set 3: I would prefer that you didn't submit this

Build breaks for me:

^[[33mtarget thumb C:^[[0m libxtables <= external/iptables/libxtables/xtables.c
external/iptables/libxtables/xtables.c:18:20: error: config.h: No such file or directory

Also, there are dozens of repeated lines previously in the build:

^[[33mtarget Generated:^[[0m libext <= external/iptables/extensions/libxt_NOTRACK.c

as well as

^[[33mtarget Generated:^[[0m libext6 <= external/iptables/extensions/libip6t_ah.c

Patch-set: 3