Update patch set 4
Patch Set 4: I would prefer that you didn't submit this

Sorry... Now I get link errors. (started a fresh build, with patches reapplied and "make installclean" before the bacon)

Error output is a bit garbled due to "-j X" make (don't know right now how to do a single-core build), but the errors clearly point to iptables:

target Executable: iptables (out/target/product/tf201/obj/EXECUTABLES/iptables_intermediates/LINKED/iptables)
prebuilt/linux-x86/toolchain/arm-linux-androideabi-4.4.x/bin/../lib/gcc/arm-linux-androideabi/4.4.3/../../../../arm-linux-androideabi/bin/ld: out/target/product/tf201/obj/STATIC_LIBRARIES/libext4_intermediates/libext4.a(initext4.o): in function init_extensions4:out/target/product/tf201/obj/STATIC_LIBRARIES/libext4_intermediates/initext4.c:25: error: undefined reference to 'libipt_addrtype_init'
prebuilt/linux-x86/toolchain/arm-linux-androideabi-4.4.x/bin/../lib/gcc/arm-linux-androideabi/4.4.3/../../../../arm-linux-androideabi/bin/ld: out/target/product/tf201/obj/STATIC_LIBRARIES/libext4_intermediates/libext4.a(initext4.o): in function init_extensions4:out/target/product/tf201/obj/STATIC_LIBRARIES/libext4_intermediates/initext4.c:27: error: undefined reference to 'libipt_ecn_init'
collect2: ld returned 1 exit status
make: *** [out/target/product/tf201/obj/EXECUTABLES/iptables_intermediates/LINKED/iptables] Error 1
make: *** Waiting for unfinished jobs....

Patch-set: 4